name: "Integration-Tests"
on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run package
      - name: Test success
        uses: ./
        with:
          target-repo: s-weigand/ipynb-share
          debug: true
      - name: Test fail
        continue-on-error: true
        uses: ./
        with:
          target-repo: s-weigand/ipynb-share
          target-state: not-a-branch
          debug: true
